/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-dim": "#0047c5",
        "primary": "#1353d8",
        "secondary-fixed-dim": "#c5d6f0",
        "background": "#f7f9fb",
        "tertiary-dim": "#564f6b",
        "error-dim": "#4f0116",
        "on-secondary": "#f7f9ff",
        "on-surface": "#2a3439",
        "on-tertiary": "#fdf7ff",
        "on-secondary-fixed": "#314055",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#a9b4b9",
        "on-error-container": "#782232",
        "inverse-surface": "#0b0f10",
        "tertiary-fixed-dim": "#c8bfdf",
        "secondary": "#506076",
        "secondary-container": "#d3e4fe",
        "primary-container": "#dbe1ff",
        "surface-tint": "#1353d8",
        "inverse-on-surface": "#9a9d9f",
        "surface-container": "#e8eff3",
        "tertiary": "#625b77",
        "primary-fixed-dim": "#c8d3ff",
        "on-surface-variant": "#566166",
        "on-tertiary-container": "#4a445e",
        "primary-fixed": "#dbe1ff",
        "surface-variant": "#d9e4ea",
        "on-primary-container": "#0046c3",
        "secondary-fixed": "#d3e4fe",
        "surface-dim": "#cfdce3",
        "inverse-primary": "#638aff",
        "surface": "#f7f9fb",
        "error": "#9e3f4e",
        "tertiary-fixed": "#d6cdee",
        "on-secondary-fixed-variant": "#4d5d73",
        "outline": "#717c82",
        "on-tertiary-fixed-variant": "#534d68",
        "surface-container-low": "#f0f4f7",
        "surface-bright": "#f7f9fb",
        "on-primary": "#f8f7ff",
        "on-primary-fixed-variant": "#0b50d5",
        "on-error": "#fff7f7",
        "on-background": "#2a3439",
        "surface-container-high": "#e1e9ee",
        "on-tertiary-fixed": "#37314a",
        "on-secondary-container": "#435368",
        "tertiary-container": "#d6cdee",
        "error-container": "#ff8b9a",
        "on-primary-fixed": "#00369b",
        "surface-container-highest": "#d9e4ea",
        "secondary-dim": "#44546a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      }
    },
  },
  plugins: [],
}